project:
  type: website

website:
  google-analytics:
    tracking-id: "G-CEC6152V08"
    anonymize-ip: true
  favicon: logo.png
  title: "Ágnes coach"
  search: false
  navbar:
    search: false
    right:
      - text: Időpontok
        icon: calendar
        href: https://calendly.com/granatne/60min
      - text: Rólam
        href: about.qmd
        icon: fingerprint
      - text: Személyi edzés
        href: dates.qmd
        icon: clipboard2-pulse
      - text: Tippek
        href: posts.qmd
        icon: balloon-heart
      - icon: chat
        href: "mailto:granatne@gmail.com"
      - icon: telephone
        href: "tel:+36303845143"
format:
  html:
    theme: [quartz, styles.scss]

editor: visual

